### ISSUE TITLE
KvikIO: Need to canonicalize dlopen'd library names

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/kvikio#200]
Documenting an offline discussion with @jakirkham in preparation of CUDA 12 bring-up on conda-forge.

Currently, there're some places where `libXXXXX.so` without any SONAME being dlopen'd, for example,
https://github.com/rapidsai/kvikio/blob/db0a3e71dccb17bbe7443a295c84aeeadb1359bc/cpp/include/kvikio/shim/cufile.hpp#L53
There will become problematic because the `libXXXXX.so` symlink is supposed to exist only in the `libXXXXX-dev` package by the stand practice of Linux distros, not in `libXXXXX` which only contains `libXXXXX.so.{major}`. The dlopen'd names need to be canonicalized.

Note: Text borrowed from Leo's issue ( https://github.com/rapidsai/cudf/issues/12708 ) and tweaked

**Comment by jakirkham** [comment]
Some comments:

* It appears we load `libcufile.so.1`. Where have we seen that in use?
* AFAICT `libcufile.so.0` is the typical name. So this looks good.
* It looks like we fallback to `libcufile.so`. Does that show up in places where `libcufile.so.0` isn't present?

**Comment by madsbk** [comment]
I have seen all of them in the wild :)
On my current workstation, I have `libcufile.so `, `libcufile.so.0`, `libcufile.so.1.4.0`, all pointing to the same library

**Comment by madsbk** [comment]
Sorry, I can't remember when I saw `libcufile.so.1` :/

**Comment by wence-** [comment]
We need to `dlopen` `libcufile.so.0` and no other. `libcufile.so` is installed in "dev" mode always pointing at the most recent "ABI-versioned" `.so`. That in turn symlinks to the actual versioned library. If both `libcufile.so.1` and `libcufile.so.0` were to exist (I do not believe that they do) they are (by definition) _ABI-incompatible_. This would mean that it is not safe to use a library built against an old version of `libcufile` with a new version (because, say, struct layouts will have changed).
