### ISSUE TITLE
[Question] Purpose of no Cuda in examples

### ISSUE THREAD

**Issue by morristai** [rapidsai/kvikio#468]
Hi,

I'm new here and just noticed there's a C++ example file, `cpp/examples/basic_no_cuda.cpp`, which uses `std::vector` instead of `cudaMalloc`. I’m curious about the benefit of doing so. Does it allocate the buffer in regular RAM instead of GPU memory? If so, what is the purpose of using Kvikio in this senario? And if not, what is the difference between CUDA and non-CUDA when using Kvikio?

**Comment by madsbk** [comment]
Yes, the no-cuda example allocates in RAM (host memory). In fact, the example does not use the GPU at all (we should make that more clear). 
The benefit of KvikIO in no-cuda mode is twofold. First it unifies the IO interface so that the same API can be used no matter the setup. Second, KvikIO will often outperform regular POSIX because of threading - try setting `KVIKIO_NTHREADS` to something greater than 1 (the default).

**Comment by morristai** [comment]
Thank you for the response, that's very clear.
