### ISSUE TITLE
[Question] CuFile GPU behavior in Compatibility Mode

### ISSUE THREAD

**Issue by fstrug** [rapidsai/kvikio#521]
When kvikio/CuFile is not running in compatibility mode it is possible to have the `cuFileReadAsync/WriteAsync` API calls executed in different cuda streams. `kvikio.CuFile.raw_read_async()` and the corresponding `raw_write_async()` function can take a `cupy.cuda.Stream` object as an argument to define which stream to perform the read/write. These functions do not support host memory and do not use posix threads.

When in compatibility mode reads are done through posix, and kvikio/CuFile parallelizes this by creating multiple posix threads. In compatibility mode during a read, would it be possible to start another read that is not blocked by the one before it with `kvikio` in another `cupy.cuda.Stream` (or something like it)? Is this stream functionallity only supported when accesing data on a GDS enabled storage in `CuFile`?

**Comment by madsbk** [comment]
> When kvikio/CuFile is not running in compatibility mode it is possible to have the `cuFileReadAsync/WriteAsync` API calls executed in different cuda streams. `kvikio.CuFile.raw_read_async()` and the corresponding `raw_write_async()` function can take a `cupy.cuda.Stream` object as an argument to define which stream to perform the read/write. 

Yes, `raw_read_async` and `raw_write_async` can be called with different cuda streams. Just make sure that the returned [`IOFutureStream`](https://github.com/rapidsai/kvikio/blob/branch-24.12/python/kvikio/kvikio/cufile.py#L10) is kept alive alive until all data has been read/written. 

> These functions do not support host memory and do not use posix threads.

Correct.

> When in compatibility mode reads are done through posix, and kvikio/CuFile parallelizes this by creating multiple posix threads. In compatibility mode during a read, would it be possible to start another read that is not blocked by the one before it with `kvikio` in another `cupy.cuda.Stream` (or something like it)? Is this stream functionallity only supported when accesing data on a GDS enabled storage in `CuFile`?

This isn't implemented in KvikIO but the workflow should work with KvikIO. Say you have 4 threads in Python, you can have each thread read a chunk of the file using their own cuda stream. Since all calls to kvikio releases the GIL, it should enable concurrent reads.
