### ISSUE TITLE
Limit pinned memory pool chunk size

### ISSUE THREAD

**Issue by vuule** [rapidsai/kvikio#72]
The size of chunks in the pinned memory pool should be limited by the slice size, since each chunk is always used by a single thread.

**Comment by madsbk** [comment]
I think this is a good idea but since it is possible to change the `task_size` (aka slice size) [between IO calls](https://github.com/rapidsai/kvikio/blob/branch-22.08/cpp/include/kvikio/file_handle.hpp#L380), [`AllocRetain`](https://github.com/rapidsai/kvikio/blob/branch-22.08/cpp/include/kvikio/posix_io.hpp#L40) will have to support reuse of different sized memory chunks.

Also notice, there is only one [memory pool](https://github.com/rapidsai/kvikio/blob/branch-22.08/cpp/include/kvikio/posix_io.hpp#L102) shared between all threads. We could change this to have each thread maintain its own bounce buffer.
